### ISSUE TITLE
Reporte 3_Interfaz Grafica

### ISSUE THREAD

**Issue by JoseMVasquezD** [SistemasTecTlaxiaco/actividad-3-practica-de-interfaz-grafica-con-interactividad-topicosa-equiporr#2]
[reporte_3_topicos_ProyectoRR.docx.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-practica-de-interfaz-grafica-con-interactividad-topicosa-equiporr/files/10777313/reporte_3_topicos_ProyectoRR.docx.pdf)

**Comment by Elisahadad** [comment]
Calificación: 14
Falta lista de Figuras y complementar desarrollo.

**Comment by josealfredo79** [comment]
Revisado...
